# Generated by Django 2.0.1 on 2018-01-29 10:04

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import trading.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LimitOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_placed', models.DateTimeField(help_text='The time at which the order was placed.', null=True)),
                ('side', models.PositiveSmallIntegerField(choices=[(trading.enums.OrderSide(1), 'Buy'), (trading.enums.OrderSide(2), 'Sell')])),
                ('quantity', models.DecimalField(decimal_places=10, help_text='Quantity of the symbol to buy/sell.', max_digits=20)),
                ('quantity_filled', models.DecimalField(blank=True, decimal_places=10, help_text='Quantity of the order that has filled.', max_digits=20, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(trading.enums.OrderState(1), 'Pending'), (trading.enums.OrderState(2), 'Placed'), (trading.enums.OrderState(3), 'Filling'), (trading.enums.OrderState(4), 'Completed'), (trading.enums.OrderState(5), 'Cancelled'), (trading.enums.OrderState(6), 'Partially cancelled')], default=trading.enums.OrderState(1))),
                ('time_closed', models.DateTimeField(help_text='The time at which the order was closed.', null=True)),
                ('exchange_order_id', models.CharField(help_text='Order ID string obtained from exchange.', max_length=255)),
                ('price', models.DecimalField(decimal_places=10, help_text='Limit price to buy below (for buy orders) or sell above (for sell orders).', max_digits=20)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MarketOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_placed', models.DateTimeField(help_text='The time at which the order was placed.', null=True)),
                ('side', models.PositiveSmallIntegerField(choices=[(trading.enums.OrderSide(1), 'Buy'), (trading.enums.OrderSide(2), 'Sell')])),
                ('quantity', models.DecimalField(decimal_places=10, help_text='Quantity of the symbol to buy/sell.', max_digits=20)),
                ('quantity_filled', models.DecimalField(blank=True, decimal_places=10, help_text='Quantity of the order that has filled.', max_digits=20, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(trading.enums.OrderState(1), 'Pending'), (trading.enums.OrderState(2), 'Placed'), (trading.enums.OrderState(3), 'Filling'), (trading.enums.OrderState(4), 'Completed'), (trading.enums.OrderState(5), 'Cancelled'), (trading.enums.OrderState(6), 'Partially cancelled')], default=trading.enums.OrderState(1))),
                ('time_closed', models.DateTimeField(help_text='The time at which the order was closed.', null=True)),
                ('exchange_order_id', models.CharField(help_text='Order ID string obtained from exchange.', max_length=255)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TradingSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_opened', models.DateTimeField(auto_now_add=True, help_text='The time at which the session was opened.', null=True)),
                ('symbol', models.CharField(help_text='Symbol, e.g. "BNBBTC"', max_length=10)),
                ('time_closed', models.DateTimeField(help_text='The time at which the session was closed.', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='marketorder',
            name='trading_session',
            field=models.ForeignKey(help_text='The trading session under which this order was placed.', on_delete=django.db.models.deletion.CASCADE, to='trading.TradingSession'),
        ),
        migrations.AddField(
            model_name='limitorder',
            name='trading_session',
            field=models.ForeignKey(help_text='The trading session under which this order was placed.', on_delete=django.db.models.deletion.CASCADE, to='trading.TradingSession'),
        ),
    ]
