# Generated by Django 2.0.1 on 2018-01-31 09:02

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import trading.enums


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuySellPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_placed', models.DateTimeField(help_text='The time at which the order was placed.', null=True)),
                ('side', models.PositiveSmallIntegerField(choices=[(trading.enums.OrderSide(1), 'Buy'), (trading.enums.OrderSide(2), 'Sell')])),
                ('price', models.DecimalField(decimal_places=10, help_text='Limit price to buy below (for buy orders) or sell above (for sell orders).', max_digits=20, null=True)),
                ('quantity', models.DecimalField(decimal_places=10, help_text='Quantity of the symbol to buy/sell.', max_digits=20)),
                ('quantity_filled', models.DecimalField(blank=True, decimal_places=10, help_text='Quantity of the order that has filled.', max_digits=20, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(trading.enums.OrderState(1), 'Pending'), (trading.enums.OrderState(2), 'Placed'), (trading.enums.OrderState(3), 'Filling'), (trading.enums.OrderState(4), 'Completed'), (trading.enums.OrderState(5), 'Cancelled'), (trading.enums.OrderState(6), 'Partially cancelled')], default=trading.enums.OrderState(1))),
                ('time_closed', models.DateTimeField(help_text='The time at which the order was closed.', null=True)),
                ('exchange_order_id', models.CharField(help_text='Order ID string obtained from exchange.', max_length=255)),
                ('trading_session', models.ForeignKey(help_text='The trading session under which this order was placed.', on_delete=django.db.models.deletion.CASCADE, to='trading.TradingSession')),
            ],
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='limitorder',
            name='trading_session',
        ),
        migrations.RemoveField(
            model_name='marketorder',
            name='trading_session',
        ),
        migrations.DeleteModel(
            name='LimitOrder',
        ),
        migrations.DeleteModel(
            name='MarketOrder',
        ),
        migrations.AddField(
            model_name='buysellpair',
            name='_first_order',
            field=models.OneToOneField(help_text='The buy/sell that opens this pair.', on_delete=django.db.models.deletion.CASCADE, related_name='buy_sell_pair_first', to='trading.Order'),
        ),
        migrations.AddField(
            model_name='buysellpair',
            name='_second_order',
            field=models.OneToOneField(help_text='The opposing buy/sell that closes this pair.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buy_sell_pair_second', to='trading.Order'),
        ),
        migrations.AddField(
            model_name='buysellpair',
            name='trading_session',
            field=models.ForeignKey(help_text='The trading session under which this pair was traded.', on_delete=django.db.models.deletion.CASCADE, related_name='buy_sell_pairs', to='trading.TradingSession'),
        ),
    ]
